[nextcloud]
listen = /run/php/php8.2-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

user = www-data
group = www-data

pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 1000

request_terminate_timeout = 300
request_slowlog_timeout = 120s
slowlog = /var/log/php/php8.2-fpm-slow.log

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

security.limit_extensions = .php .phar

pm.status_path = /fpm-status
ping.path = /fpm-ping
ping.response = pong

access.log = /var/log/php/php8.2-fpm-access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f"